2022-12-05T18:15:46.513+0800	[31mERROR[0m	nacos_server/nacos_server.go:75	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:15:46.515+0800	[34mINFO[0m	naming_client/push_receiver.go:80	udp server start, port: 55081
2022-12-05T18:15:46.515+0800	[34mINFO[0m	util/common.go:94	Local IP:192.168.2.2
2022-12-05T18:15:46.516+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55081"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh&app=&clusters=&udpPort=55081&healthyOnly=false": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T18:15:46.516+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55081"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?healthyOnly=false&clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh&app=&clusters=&udpPort=55081": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T18:15:46.519+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55081"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?serviceName=DEFAULT_GROUP@@hh&app=&clusters=&udpPort=55081&healthyOnly=false&clientIP=192.168.2.2&namespaceId=": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T18:15:46.519+0800	[31mERROR[0m	naming_client/host_reactor.go:144	QueryList return error!serviceName:DEFAULT_GROUP@@hh cluster: err:retry3times request failed,err=Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?serviceName=DEFAULT_GROUP@@hh&app=&clusters=&udpPort=55081&healthyOnly=false&clientIP=192.168.2.2&namespaceId=": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:15:51.516+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:15:56.517+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:01.517+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:06.518+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:11.519+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:16.519+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:21.520+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:26.523+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:31.523+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:36.524+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:41.527+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:46.527+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T18:16:51.528+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:15:39.645+0800	[31mERROR[0m	nacos_server/nacos_server.go:75	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:15:39.645+0800	[34mINFO[0m	naming_client/push_receiver.go:80	udp server start, port: 55893
2022-12-05T19:15:39.645+0800	[34mINFO[0m	util/common.go:94	Local IP:192.168.2.2
2022-12-05T19:15:39.646+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55893"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?udpPort=55893&healthyOnly=false&clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh&app=&clusters=": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:15:39.646+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55893"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh&app=&clusters=&udpPort=55893&healthyOnly=false": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:15:39.646+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55893"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?app=&clusters=&udpPort=55893&healthyOnly=false&clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:15:39.647+0800	[31mERROR[0m	naming_client/host_reactor.go:144	QueryList return error!serviceName:DEFAULT_GROUP@@hh cluster: err:retry3times request failed,err=Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?app=&clusters=&udpPort=55893&healthyOnly=false&clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:15:44.646+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:15:49.647+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:15:54.648+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:15:59.648+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:16:04.649+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:16:09.650+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:16:14.652+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:17:32.781+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022-12-05T19:17:46.925+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:17:51.941+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:17:56.942+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:01.943+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:06.944+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:11.945+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:16.946+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:21.946+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:26.947+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:31.948+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:36.949+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:41.950+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:46.951+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:51.951+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:18:56.952+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:19:01.968+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:19:06.969+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:19:11.970+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:19:16.971+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:20:00.241+0800	[31mERROR[0m	nacos_server/nacos_server.go:75	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:20:00.241+0800	[34mINFO[0m	naming_client/push_receiver.go:80	udp server start, port: 55186
2022-12-05T19:20:00.241+0800	[34mINFO[0m	util/common.go:94	Local IP:192.168.2.2
2022-12-05T19:20:00.242+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55186"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?healthyOnly=false&clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh&app=&clusters=&udpPort=55186": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:20:00.242+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55186"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?namespaceId=&serviceName=DEFAULT_GROUP@@hh&app=&clusters=&udpPort=55186&healthyOnly=false&clientIP=192.168.2.2": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:20:00.242+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hh","udpPort":"55186"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?clusters=&udpPort=55186&healthyOnly=false&clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh&app=": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:20:00.242+0800	[31mERROR[0m	naming_client/host_reactor.go:144	QueryList return error!serviceName:DEFAULT_GROUP@@hh cluster: err:retry3times request failed,err=Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?clusters=&udpPort=55186&healthyOnly=false&clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hh&app=": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:20:05.242+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:20:10.243+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:20:15.243+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:20:35.326+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
2022-12-05T19:20:35.326+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hhh","udpPort":"55186"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?serviceName=DEFAULT_GROUP@@hhh&app=&clusters=&udpPort=55186&healthyOnly=false&clientIP=192.168.2.2&namespaceId=": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:20:35.327+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hhh","udpPort":"55186"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?app=&clusters=&udpPort=55186&healthyOnly=false&clientIP=192.168.2.2&namespaceId=&serviceName=DEFAULT_GROUP@@hhh": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:20:35.328+0800	[31mERROR[0m	nacos_server/nacos_server.go:230	api</v1/ns/instance/list>,method:<GET>, params:<{"app":"","clientIP":"192.168.2.2","clusters":"","healthyOnly":"false","namespaceId":"","serviceName":"DEFAULT_GROUP@@hhh","udpPort":"55186"}>, call domain error:<Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?serviceName=DEFAULT_GROUP@@hhh&app=&clusters=&udpPort=55186&healthyOnly=false&clientIP=192.168.2.2&namespaceId=": dial tcp 127.0.0.1:8848: connect: connection refused> , result:<>
2022-12-05T19:20:35.329+0800	[31mERROR[0m	naming_client/host_reactor.go:144	QueryList return error!serviceName:DEFAULT_GROUP@@hhh cluster: err:retry3times request failed,err=Get "http://127.0.0.1:8848/nacos/v1/ns/instance/list?serviceName=DEFAULT_GROUP@@hhh&app=&clusters=&udpPort=55186&healthyOnly=false&clientIP=192.168.2.2&namespaceId=": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:20:40.796+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
2022-12-05T19:20:45.797+0800	[31mERROR[0m	security/security_proxy.go:84	login has error Post "http://127.0.0.1:8848/nacos/v1/auth/users/login": dial tcp 127.0.0.1:8848: connect: connection refused
